#!/usr/bin/env python3
import subprocess
import sys


def main():
    if len(sys.argv) != 4:
        print('Wrong number of arguments')
        sys.exit(0)

    year = sys.argv[1]
    day = sys.argv[2].zfill(2)
    part = sys.argv[3]

    command = f"cat year_{year}/inputs/{day}.txt | python -c 'from year_{year}.day_{day} import part{part}; part{part}()'"

    ps = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = ps.communicate()[0]
    print(output.decode("ascii").rstrip("\r\n"))


if __name__ == "__main__":
    main()
