#!/usr/bin/env python
from pathlib import Path

import requests
import sys


def get_cookie() -> str:
    with open(Path('.session_cookie')) as f:
        lines = f.readlines()
    return lines[0]


def main() -> None:
    if len(sys.argv) != 2:
        print('Wrong number of arguments')
        sys.exit(0)

    cookie = get_cookie()
    day = sys.argv[1]
    headers = {'session': cookie}
    url = f'https://adventofcode.com/2021/day/{day}/input'

    session = requests.Session()
    resp = session.get(url, cookies=headers)

    in_file = open(f'inputs/{day.zfill(2)}.txt', 'w')
    in_file.write(resp.text)
    in_file.close()


if __name__ == "__main__":
    sys.exit(main())
