#!/usr/bin/env python3
import subprocess
import sys
from pathlib import Path

import requests


def get_cookie() -> str:
    with open(Path('.session_cookie')) as f:
        lines = f.readlines()
    return lines[0]


def main():
    if len(sys.argv) != 3:
        print('Wrong number of arguments')
        sys.exit(0)

    day = sys.argv[1].zfill(2)
    part = sys.argv[2]

    command = f"cat inputs/{day}.txt | python -c 'from days.day_{day} import part{part}; part{part}()'"

    ps = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output = ps.communicate()[0]
    answer = output.decode("ascii").rstrip("\r\n")

    cookie = get_cookie()
    headers = {'session': cookie}
    url = f'https://adventofcode.com/2021/day/{day}/answer'
    print(f"{url=}")

    session = requests.Session()
    resp = session.post(url, cookies=headers, data={"level": part, "answer": answer})
    print(resp.text)


if __name__ == "__main__":
    main()
